### ISSUE TITLE
Elasticity no longer works with Meteor

### ISSUE THREAD

**Issue by G-ram** [nothingisdead/meteor-elasticity#1]
Hey,

   Just wanted to let you know that your package does not work with the current Meteor version. I used your example code and even edited your package to prevent the checking error that occurs when you don't check parameters in publish methods or meteor methods. I got it to return an empty results array with no ids or objects even when I queried for the simplest of fields.

Cheers!

**Comment by nothingisdead** [comment]
Thank you!

I will take a look at it when I get a chance.

**Comment by bompi88** [comment]
Any news on this?

**Comment by nothingisdead** [comment]
Hi,

Sorry for the lack of updates. I am working on rewriting this package, both to get it working with Meteor 0.9 as well as to simplify index creation and searching. I'm also removing some features that now seem like premature optimizations. It should be ready to publish tonight or tomorrow night.

Thanks!

**Comment by bompi88** [comment]
That sounds awesome! I cannot wait to take a look :)

**Comment by nothingisdead** [comment]
Hi,

I just published a new version of this package that works with Meteor 1.0. The usage has changed drastically, but I provided a simple example in the readme for now.

Thanks for your interest!
